### ISSUE TITLE
ListingProfile Objects

### ISSUE THREAD

**Issue by ljbergmann** [Alpha-Trader/AlphaTraderApiBundle#117]
The validation of the deserialized objects is not working 100%.

```php
$result =   $this->get('jms_serializer')->deserialize('{
  "code": 400,
  "messagePrototype": {
    "message": "Listing does not exist",
    "substitutions": [],
    "filledString": "Listing does not exist"
  },
  "message": "Listing does not exist"
}',"Alphatrader\\ApiBundle\\Model\\ListingProfile","json");
```

if you check the $result with the isGuiltyResponse method the result is true, which is obviously wrong.

**Comment by Tr0nYx** [comment]
dont use the deserialize function from the jmsserializer yourself, just call [parseResponse('Namespace','json')](https://github.com/Alpha-Trader/AlphaTraderApiBundle/blob/v.1.1.0/src/Api/ApiClient.php#L166). 
So your code should look like this:
```php
$result =  $this->client->parseResponse('{
  "code": 400,
  "messagePrototype": {
	"message": "Listing does not exist",
	"substitutions": [],
	"filledString": "Listing does not exist"
  },
  "message": "Listing does not exist"
}',"Alphatrader\\ApiBundle\\Model\\ListingProfile","json");
```
parseResponse is typehinted with psr-7 ResponseInterface from guzzle, if you need it with strings, PR´s are welcome

**Comment by ljbergmann** [comment]
The problem would be the same, the isGuiltyResponse is not working properly:

```php
$result =  $this->client->parseResponse('{
  "code": 400,
  "messagePrototype": {
	"message": "Listing does not exist",
	"substitutions": [],
	"filledString": "Listing does not exist"
  },
  "message": "Listing does not exist"
}',"Alphatrader\\ApiBundle\\Model\\ListingProfile","json");

```

if you check the $result with the [isGuiltyResponse  ](https://github.com/Alpha-Trader/AlphaTraderApiBundle/blob/master/src/Api/ApiClient.php#L184) the result is true, because some values aren't null. To give an example ```getPrices14dDates``` returns a empty string.
